### ISSUE TITLE
antlr4 project creation wizard not over-riding the default location

### ISSUE THREAD

**Issue by vedil** [antlr4ide/antlr4ide#71] opened 2014-07-02 09:49 UTC
I have tried to create a antlr project where i gave a different location than the default one. it still creates in default location.

**Comment by HSorensen** [comment] 2016-11-15 19:03
I can confirm this bug is still present:

New project wizard:
![image](https://cloud.githubusercontent.com/assets/5041461/20319278/5c23baec-ab22-11e6-8985-34cf3fe040d7.png)

Still placed the project in the Workspace directory
![image](https://cloud.githubusercontent.com/assets/5041461/20319440/f1f3ba72-ab22-11e6-8e65-d14d4604cb5c.png)

```
ANTLR Tool v4.5.2-SNAPSHOT (C:\Users\076946\git\antlr4\tool\target\antlr4-4.5.2-SNAPSHOT.jar)
Hello.g4 -o C:\workspace\TestAntlrWizard\target\generated-sources\antlr4 -listener -visitor -lib -encoding UTF-8

BUILD SUCCESSFUL
Total time: 792 millisecond(s)
```

**Comment by HSorensen** [comment] 2016-11-15 21:32
Giving up ... @arifogel @timeraider4u Can you figure out how this file
`/antlr4ide/antlr4ide.ui/src/generated/java/com/github/jknack/antlr4ide/ui/wizard/Antlr4NewProjectWizard.java`
gets generated ?

**Comment by arifogel** [comment] 2016-11-15 21:38
I can take a look this weekend if it's still an issue then.

**Comment by HSorensen** [comment] 2016-11-15 21:55
I would really like to learn how the code generator works, so please share what you find.

The error seems to be in the generated java code:
```
/**
 * Use this method to read the project settings from the wizard pages and feed them into the project info class.
 */
@Override
protected IProjectInfo getProjectInfo() {
	com.github.jknack.antlr4ide.ui.wizard.Antlr4ProjectInfo projectInfo = new com.github.jknack.antlr4ide.ui.wizard.Antlr4ProjectInfo();
	projectInfo.setProjectName(mainPage.getProjectName());
	return projectInfo;
}
```

it seems the project directory is not copied from the Wizard's mainPage object to the projectInfo.

**Comment by timeraider4u** [comment] 2016-11-15 23:07
If I get it right, _/antlr4ide.ui/src/generated/java/com/github/jknack/antlr4ide/ui/wizard/Antlr4NewProjectWizard.java_ is generated by the _projectWizard.SimpleProjectWizardFragment_ in the mwe2 workflow file _/antlr4ide.core/src/main/java/com/github/jknack/antlr4ide/GenerateAntlr4.mwe2_ at line 147. I am currently reading the description at http://jevopisdeveloperblog.blogspot.co.at/2011/02/extract-xtext-project-wizard.html Maybe this helps you too!

**Comment by HSorensen** [comment] 2016-11-15 23:54
Yeah just reading that too.
I just can see where the template for the generated java file is coming from.
It has to be something here from the GenrateAntlr4.mwe2 file:
```java
 fragment = projectWizard.SimpleProjectWizardFragment auto-inject {
   generatorProjectName = "${projectName}.generator"
   fileExtension = fileExtensions
}
```

**Comment by HSorensen** [comment] 2016-11-16 00:14
getting closer:
https://eclipse.org/Xtext/documentation/310_eclipse_support.html#project-wizard

**Comment by HSorensen** [comment] 2016-11-16 05:34
Ok, after some searching I decided to look at the xtext source code:
https://github.com/eclipse/xtext-core/blob/master/org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/ui/projectWizard/SimpleProjectWizardFragment2.xtend

This source the code contain the template for the generated wizard code:
```java
def generateNewProjectWizard() {
...
...
/**
			 * Use this method to add pages to the wizard.
			 * The one-time generated version of this class will add a default new project page to the wizard.
			 */
			@Override
			public void addPages() {
				mainPage = createMainPage("basicNewProjectPage");
				mainPage.setTitle("«grammar.simpleName» Project");
				mainPage.setDescription("Create a new «grammar.simpleName» project.");
				addPage(mainPage);
			}
		
			protected «creationPageClassName» createMainPage(String pageName) {
				return new «creationPageClassName»(pageName);
			}
		
			/**
			 * Use this method to read the project settings from the wizard pages and feed them into the project info class.
			 */
			@Override
			protected IExtendedProjectInfo getProjectInfo() {
				«projectInfoClass.simpleName» projectInfo = new «projectInfoClass.simpleName»();
				projectInfo.setProjectName(mainPage.getProjectName());
				if (!mainPage.useDefaults()) {
					projectInfo.setLocationPath(mainPage.getLocationPath());
				}
				return projectInfo;
			}

```
but notice this part:
```java
                if (!mainPage.useDefaults()) {
                    projectInfo.setLocationPath(mainPage.getLocationPath());
                }
```
is missing for the current version used by antlr4ide so the solution might be to simple update xtext.

**Comment by HSorensen** [comment] 2016-11-16 06:22
Probably a good time to study:
[Eclipse 15 mins Xtext tutorial](https://eclipse.org/Xtext/documentation/102_domainmodelwalkthrough.html)
[DSL Tutorial](http://www.robertwloch.net/2016/08/the-few-hours-minutes-shiny-dsl-product-tutorial/)

**Comment by HSorensen** [comment] 2016-11-16 19:52
Look at the PR #161 

![image](https://cloud.githubusercontent.com/assets/5041461/20362960/4109c58c-abf2-11e6-8685-5b497adb5092.png)

This solves the bug, **BUT** there are some conceptual issues with the proposed processing because this effectively ignores the genrated wizard code.

I might be misreading this but I don't think the wizard generation framework is supposed to be used in the manner antlr4ide is using it. Most of the references I have seen mentions run the wizard generator once and integrate the generated results into the application. This explains why the code template is hardcoded into the xtext framework.
Thoughts?

**Comment by HSorensen** [comment] 2016-11-18 03:09
i'll close this bug. We need to revisit the whole code generation issue at some point. But no reason to keep this bug unresolved.

**Closed by HSorensen** 2016-11-18 03:09 UTC
Labels: bug
