### ISSUE TITLE
[BUG] Generated sources are not being placed in the folder specified by the @header

### ISSUE THREAD

**Issue by sithys** [antlr4ide/antlr4ide#154] opened 2016-11-09 04:50 UTC
![generatedsources](https://cloud.githubusercontent.com/assets/2238840/20127432/bd08fad6-a5f3-11e6-8f12-1f8d21035a30.PNG)

All of my grammar files contain the same package specification in the @header section. The code being generated is correctly being placed in a sub-folder that corresponds to the package name, except in one case, as highlighted in this image.

No steps for reproduction. The behavior seems to be random. Once a grammar file starts exhibiting this behavior, it never stops, even if you delete the file and add a file with the same name and contents, clean, restart eclipse, or any combination of any of all of these steps.

**Comment by sithys** [comment] 2016-11-10 03:47
I did find one method of reproduction. Click a grammar file that has an @header and click the Run button in Eclipse. It will build that grammar into the wrong folder.

**Comment by HSorensen** [comment] 2016-11-10 19:08
I cannot reproduce this, but the problem sounds familiar.
Did you try to reproduce with the latest version of Antlr4IDE ?

**Comment by HSorensen** [comment] 2016-11-15 06:38
Still cannot reproduce this error.

I tried this grammar, and the run button.

```antlr
grammar testissue154;
@header { package issue.no154 ;}
file: hdr row+ ;
hdr : row ;
row : field (',' field)* '\r'? '\n' ;
field
    : TEXT
    | STRING
    |
    ;
TEXT   : ~[,\n\r"]+ ;
STRING : '"' ('""'|~'"')* '"' ;
```
Can you check if you have an old launch configuration for the grammar file?

**Comment by HSorensen** [comment] 2016-12-01 05:34
@sithys can you check if you have an external run configuration defined for the JSON.g4 grammar file?
![image](https://cloud.githubusercontent.com/assets/5041461/20782870/a1e8a0aa-b744-11e6-9aa1-2f666112b795.png)

if you do the run config will take precedence over the workspace/project settings.

**Comment by timeraider4u** [comment] 2016-12-01 12:32
@HSorensen do you think that this bug is related to issue #137?

**Comment by HSorensen** [comment] 2016-12-01 16:35
It is possible related to #137.
But after I removed the external run config for the file the problem did not occur.

**Comment by sithys** [comment] 2016-12-01 17:36
When I click Run on one of my g4 files it does in fact create an external configuration under Run -> External Tools -> External Tool Configurations

When I delete it the behavior returns to normal.

**Comment by HSorensen** [comment] 2016-12-02 00:15
I think part of the problem is afaics antlr4ide creates a file-specific runtime config when you choose `Run As->Generate Antlr Recognizer`

![image](https://cloud.githubusercontent.com/assets/5041461/20818207/13e1659c-b7e1-11e6-95f8-c8f1ebe64cf9.png)

I think we need to create an option to use the RunAs with projects, without creating an external run configuration for the file.

**Comment by sithys** [comment] 2016-12-17 17:43
I have full steps for reproduction now:

1) Check Properties -> ANTLR 4 -> Tool -> Generate Parse Tree Visitors
2) Select a grammar and click Run

This seems to reliably reproduce the error.

**Comment by timeraider4u** [comment] 2016-12-19 12:10
Sounds like a duplicate of #137 to me and, as a result, I will close this issue as a duplicate.

**Closed by timeraider4u** 2016-12-19 12:10 UTC
